name: Add Cache Headers
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup HTTPD
      run: |
        echo "Adding .htaccess for cache headers"
        cat > .htaccess << EOF
        <FilesMatch "\.(webp|css|js)$">
          Header set Cache-Control "max-age=31536000, public"
        </FilesMatch>
        EOF
